{{- if .Values.deviceplugin.ascend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.deviceplugin.ascend.resourcePrefix | default "hami-device-plugin" }}-volcano-ascend
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: {{ .Values.deviceplugin.ascend.resourcePrefix | default "hami-device-plugin" }}-volcano-ascend
{{- end }}