actions: "enqueue, allocate, backfill"
tiers:
- plugins:
  - name: priority
    enableNodeOrder: false
  - name: gang
    enableNodeOrder: false
  - name: conformance
    enableNodeOrder: false
  - name: volcano-npu_v6.0.RC2.1_linux
- plugins:
  - name: drf
    enableNodeOrder: false
  - name: deviceshare
    arguments:
      deviceshare.VGPUEnable: true
      deviceshare.KnownGeometriesCMName: "volcano-vgpu-device-config"
      deviceshare.KnownGeometriesCMNamespace: {{ .Release.Namespace | quote }}
      deviceshare.AscendVGPUEnable: true  # enable npu
  - name: predicates
    enableNodeOrder: false
    arguments:
      predicate.GPUSharingEnable: false
      predicate.GPUNumberEnable: false
  - name: proportion
    enableNodeOrder: false
  - name: nodeorder
  - name: binpack
    enableNodeOrder: false
configurations:
  - name: init-params
    arguments: {"grace-over-time":"900","presetVirtualDevice":"true","nslb-version":"1.0","shared-tor-num":"2",
"useClusterInfoManager":"true","super-pod-size": "48", "reserve-nodes": "2"}