{{- if .Values.deviceplugin.nvidia.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.deviceplugin.nvidia.resourcePrefix | default "hami-device-plugin" }}-volcano-nvidia
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["nodes/status"]
  verbs: ["patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "update", "patch", "watch"]
{{- end }}
