{{- if .Values.deviceplugin.nvidia.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.deviceplugin.nvidia.resourcePrefix | default "hami-device-plugin" }}-volcano-nvidia
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: {{ .Values.deviceplugin.nvidia.resourcePrefix | default "hami-device-plugin" }}-volcano-nvidia
{{- end }}